const {chromium}=require('@playwright/test');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('https://nogajeng.vercel.app',{waitUntil:'networkidle'});
 await page.locator('.menu-card').last().waitFor();
 if(await page.locator('.menu-card').count()!==16)throw Error('Menu count');
 await page.screenshot({path:'../video-review/site-desktop.png'});
 await page.getByRole('button',{name:'식사 메뉴',exact:true}).click();
 if(await page.locator('.menu-card').count()!==5)throw Error('Meal filter');
 await page.getByRole('button',{name:'곁들임',exact:true}).click();
 if(await page.locator('.menu-card').count()!==4)throw Error('Side filter');
 await page.getByRole('button',{name:'전체 메뉴',exact:true}).click();
 const broken=await page.locator('.menu-card img').evaluateAll(imgs=>imgs.filter(i=>i.complete&&i.naturalWidth===0).map(i=>i.src));
 if(broken.length)throw Error('Broken images '+broken);
 await page.locator('#reserve').scrollIntoViewIfNeeded();
 await page.locator('[name=date]').fill('2026-12-20');await page.locator('[name=time]').selectOption('12:00');await page.locator('[name=name]').fill('확인용');await page.locator('[name=guests]').fill('101');
 if(await page.locator('#reservation-form').evaluate(f=>f.checkValidity()))throw Error('Guest bound missing');
 await page.locator('[name=guests]').fill('4');await page.locator('[name=phone]').fill('01000000000');await page.locator('[name=consent]').check();
 if(!await page.locator('#reservation-form').evaluate(f=>f.checkValidity()))throw Error('Valid form rejected');
 await page.setViewportSize({width:390,height:844});await page.goto('https://nogajeng.vercel.app',{waitUntil:'networkidle'});
 await page.screenshot({path:'../video-review/site-mobile.png',fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.reload({waitUntil:'networkidle'});await page.locator('#fire').scrollIntoViewIfNeeded();
 if(!await page.locator('#fire').evaluate(v=>v.paused))throw Error('Reduced motion autoplay');
 if(errors.length)throw Error(errors.join(';'));
 console.log('PASS: 16 menus, filters, image load, form bounds, mobile width, reduced motion, no JS errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
