from pathlib import Path
import json
p=Path('public/index.html');s=p.read_text(encoding='utf-8-sig')
s=s.replace('<script src="/app.js" defer></script>','<script src="/app.js" defer></script><link rel="stylesheet" href="/booking.css"><script src="/booking.js" defer></script>')
start=s.index('<form id="reservation-form">');end=s.index('</form>',start)+len('</form>')
s=s[:start]+'''<form id="reservation-form"><h3>온라인 예약 신청</h3><p>신청 후 식당 확인을 거쳐 예약이 확정됩니다.</p><div class="form-grid"><label>방문 날짜<input type="date" name="date" required></label><label>방문 시간<select name="time" required><option value="">시간 선택</option></select></label><label>인원<input type="number" name="guests" min="1" max="100" value="2" required></label><label>예약자 이름<input name="name" autocomplete="name" maxlength="30" required placeholder="이름"></label></div><label>휴대폰 번호<input type="tel" name="phone" autocomplete="tel" required maxlength="13" placeholder="010-1234-5678"></label><label>요청사항<textarea name="note" maxlength="300" rows="3" placeholder="좌석 요청 등을 적어주세요. 민감한 개인정보는 적지 말아주세요."></textarea></label><div class="honeypot" aria-hidden="true"><label>웹사이트<input name="website" tabindex="-1" autocomplete="off"></label></div><details><summary>예약 개인정보 수집·이용 안내</summary><p>수집 항목: 이름, 휴대폰 번호, 방문 일시, 인원, 요청사항.<br>이용 목적: 예약 접수·확인·변경 및 고객 연락.<br>보관 기간: 방문일로부터 30일 후 자동 삭제(매일 정리).<br>예약 정보는 비공개 저장소에 보관하며 식당 관리자만 확인합니다. 동의를 거부할 수 있으나 온라인 예약 신청은 이용할 수 없습니다. 전화 예약은 043-225-9595로 문의해 주세요.</p><a class="privacy-link" href="/privacy.html" target="_blank" rel="noopener">개인정보 처리 안내 전체 보기 ↗</a></details><label class="consent"><input type="checkbox" name="consent" required><span>[필수] 예약을 위한 개인정보 수집·이용에 동의합니다.</span></label><p class="small-note">오늘부터 90일 이내 신청 가능합니다. 설날·추석 당일 휴무.<br>자동 문자 알림은 발송되지 않습니다. 접수번호와 조회코드로 확정 여부를 확인해 주세요.</p><button class="button gold full" type="submit">예약 신청하기</button><p id="form-status" role="status"></p><div id="booking-result" class="booking-result" hidden aria-live="polite"></div><button id="new-booking" type="button" hidden>새 예약 신청</button><a class="text-link" href="#booking-check">신청한 예약 조회·취소</a></form>'''+s[end:]
lookup='''<section class="section lookup-section" id="booking-check"><span class="eyebrow">MY RESERVATION</span><h2>예약 조회·취소</h2><p>신청할 때 받은 접수번호와 조회코드를 입력해 주세요.<br>코드를 잊으셨다면 043-225-9595로 문의해 주세요.</p><form id="booking-lookup"><div class="form-grid"><label>접수번호<input id="lookup-id" required maxlength="12" autocomplete="off" spellcheck="false"></label><label>조회코드<input id="lookup-code" required maxlength="20" autocomplete="off" spellcheck="false"></label></div><button class="button gold">예약 조회</button></form><p id="lookup-status" role="status"></p><div id="lookup-result" class="booking-result" hidden></div><button id="cancel-booking" class="button" type="button" hidden>이 예약 취소하기</button></section>'''
s=s.replace('<section class="section visit" id="visit">',lookup+'<section class="section visit" id="visit">')
s=s.replace('예약 내용 작성 ↗','온라인 예약 ↗').replace('예약 내용 작성','온라인 예약')
s=s.replace('© <span id="year"></span> NOGAJENG','© <span id="year"></span> NOGAJENG<br><a href="/privacy.html">개인정보 처리 안내</a> · <a href="/admin.html" rel="nofollow">예약 관리</a>')
p.write_text(s,encoding='utf-8')
p=Path('public/app.js');s=p.read_text(encoding='utf-8-sig');start=s.index('function message()');end=s.index("document.querySelector('#copy-address')",start);s=s[:start]+s[end:];s=s.replace('form.elements.date.min=localDate();','form.elements.date.min=localDate();\nform.elements.date.max=new Intl.DateTimeFormat(\'sv-SE\',{timeZone:\'Asia/Seoul\'}).format(new Date(Date.now()+90*86400000));');p.write_text(s,encoding='utf-8')
p=Path('vercel.json');config=json.loads(p.read_text());config['crons']=[{'path':'/api/cleanup','schedule':'0 18 * * *'}];config['functions']={'api/*.js':{'maxDuration':60}};p.write_text(json.dumps(config,indent=2),encoding='utf-8')
